// Generated by gencpp from file tfpose_ros/GetPersons.msg
// DO NOT EDIT!


#ifndef TFPOSE_ROS_MESSAGE_GETPERSONS_H
#define TFPOSE_ROS_MESSAGE_GETPERSONS_H

#include <ros/service_traits.h>


#include <tfpose_ros/GetPersonsRequest.h>
#include <tfpose_ros/GetPersonsResponse.h>


namespace tfpose_ros
{

struct GetPersons
{

typedef GetPersonsRequest Request;
typedef GetPersonsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPersons
} // namespace tfpose_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tfpose_ros::GetPersons > {
  static const char* value()
  {
    return "eac1ac7f48af0b16a14c17b14c3bebc0";
  }

  static const char* value(const ::tfpose_ros::GetPersons&) { return value(); }
};

template<>
struct DataType< ::tfpose_ros::GetPersons > {
  static const char* value()
  {
    return "tfpose_ros/GetPersons";
  }

  static const char* value(const ::tfpose_ros::GetPersons&) { return value(); }
};


// service_traits::MD5Sum< ::tfpose_ros::GetPersonsRequest> should match 
// service_traits::MD5Sum< ::tfpose_ros::GetPersons > 
template<>
struct MD5Sum< ::tfpose_ros::GetPersonsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tfpose_ros::GetPersons >::value();
  }
  static const char* value(const ::tfpose_ros::GetPersonsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tfpose_ros::GetPersonsRequest> should match 
// service_traits::DataType< ::tfpose_ros::GetPersons > 
template<>
struct DataType< ::tfpose_ros::GetPersonsRequest>
{
  static const char* value()
  {
    return DataType< ::tfpose_ros::GetPersons >::value();
  }
  static const char* value(const ::tfpose_ros::GetPersonsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tfpose_ros::GetPersonsResponse> should match 
// service_traits::MD5Sum< ::tfpose_ros::GetPersons > 
template<>
struct MD5Sum< ::tfpose_ros::GetPersonsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tfpose_ros::GetPersons >::value();
  }
  static const char* value(const ::tfpose_ros::GetPersonsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tfpose_ros::GetPersonsResponse> should match 
// service_traits::DataType< ::tfpose_ros::GetPersons > 
template<>
struct DataType< ::tfpose_ros::GetPersonsResponse>
{
  static const char* value()
  {
    return DataType< ::tfpose_ros::GetPersons >::value();
  }
  static const char* value(const ::tfpose_ros::GetPersonsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TFPOSE_ROS_MESSAGE_GETPERSONS_H
