// Generated by gencpp from file tfpose_ros/Persons3D.msg
// DO NOT EDIT!


#ifndef TFPOSE_ROS_MESSAGE_PERSONS3D_H
#define TFPOSE_ROS_MESSAGE_PERSONS3D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tfpose_ros/Person3D.h>
#include <std_msgs/Header.h>

namespace tfpose_ros
{
template <class ContainerAllocator>
struct Persons3D_
{
  typedef Persons3D_<ContainerAllocator> Type;

  Persons3D_()
    : persons()
    , image_w(0)
    , image_h(0)
    , header()  {
    }
  Persons3D_(const ContainerAllocator& _alloc)
    : persons(_alloc)
    , image_w(0)
    , image_h(0)
    , header(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::tfpose_ros::Person3D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::tfpose_ros::Person3D_<ContainerAllocator> >::other >  _persons_type;
  _persons_type persons;

   typedef uint32_t _image_w_type;
  _image_w_type image_w;

   typedef uint32_t _image_h_type;
  _image_h_type image_h;

   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;





  typedef boost::shared_ptr< ::tfpose_ros::Persons3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tfpose_ros::Persons3D_<ContainerAllocator> const> ConstPtr;

}; // struct Persons3D_

typedef ::tfpose_ros::Persons3D_<std::allocator<void> > Persons3D;

typedef boost::shared_ptr< ::tfpose_ros::Persons3D > Persons3DPtr;
typedef boost::shared_ptr< ::tfpose_ros::Persons3D const> Persons3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tfpose_ros::Persons3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tfpose_ros::Persons3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tfpose_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'tfpose_ros': ['/home/pedroildefonso/baxter_project/workspace/src/tf-pose-estimation/msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tfpose_ros::Persons3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tfpose_ros::Persons3D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfpose_ros::Persons3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfpose_ros::Persons3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfpose_ros::Persons3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfpose_ros::Persons3D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tfpose_ros::Persons3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c752c4c2da8af796a9eef30d5dcd52c0";
  }

  static const char* value(const ::tfpose_ros::Persons3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc752c4c2da8af796ULL;
  static const uint64_t static_value2 = 0xa9eef30d5dcd52c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::tfpose_ros::Persons3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tfpose_ros/Persons3D";
  }

  static const char* value(const ::tfpose_ros::Persons3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tfpose_ros::Persons3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Person3D[] persons\n\
uint32 image_w\n\
uint32 image_h\n\
Header header\n\
================================================================================\n\
MSG: tfpose_ros/Person3D\n\
uint32 person_id\n\
BodyPartElm3D nose\n\
BodyPartElm3D neck\n\
BodyPartElm3D right_shoulder\n\
BodyPartElm3D right_elbow\n\
BodyPartElm3D right_wrist\n\
BodyPartElm3D left_shoulder\n\
BodyPartElm3D left_elbow\n\
BodyPartElm3D left_wrist\n\
BodyPartElm3D right_hip\n\
BodyPartElm3D right_knee\n\
BodyPartElm3D right_ankle\n\
BodyPartElm3D left_hip\n\
BodyPartElm3D left_knee\n\
BodyPartElm3D left_ankle\n\
BodyPartElm3D right_eye\n\
BodyPartElm3D left_eye\n\
BodyPartElm3D right_ear\n\
BodyPartElm3D left_ear\n\
================================================================================\n\
MSG: tfpose_ros/BodyPartElm3D\n\
uint32 part_id\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 confidence\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::tfpose_ros::Persons3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tfpose_ros::Persons3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.persons);
      stream.next(m.image_w);
      stream.next(m.image_h);
      stream.next(m.header);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Persons3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tfpose_ros::Persons3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tfpose_ros::Persons3D_<ContainerAllocator>& v)
  {
    s << indent << "persons[]" << std::endl;
    for (size_t i = 0; i < v.persons.size(); ++i)
    {
      s << indent << "  persons[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tfpose_ros::Person3D_<ContainerAllocator> >::stream(s, indent + "    ", v.persons[i]);
    }
    s << indent << "image_w: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_w);
    s << indent << "image_h: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.image_h);
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TFPOSE_ROS_MESSAGE_PERSONS3D_H
